@base=http://localhost:5019

### Install shopify app
GET {{base}}/api/shopify/install?shop=shopify-app-1.myshopify.com

### Install callback shopify app
GET {{base}}/api/shopify/callback

### Uninstall shopify app
POST https://patient-snail-moved.ngrok-free.app/webhook/uninstall
Content-Type: application/json

{
   
}

### Get Shop Info
GET {{base}}/api/shop/info