# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c572402fb6e121b9ebdfe72d6cf3643"
name = "My first app"
handle = "my-first-app-1318"
application_url = "https://patient-snail-moved.ngrok-free.app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [ "https://patient-snail-moved.ngrok-free.app/" ]

[webhooks]
api_version = "2024-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "/webhook/uninstall"

[pos]
embedded = false