services:
  postgres:
    container_name: shopify_app_postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopify_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped  
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: notifly
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3360
    ports:
      - "3360:3360"
    volumes:
      - mysql-data:/var/lib/mysql  
volumes:
  postgres-data:
  mysql-data:  